name: Close inactive issues
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 15
          days-before-issue-close: 15
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 15 days with no activity. It will be closed in 5 days if there are no modifications."
          close-issue-message: "This issue was closed because it has been inactive for 15 days since being marked as stale."
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 7 days with no activity. It will be closed in 5 days if there are no modifications."
          close-pr-message: "This PR was closed because it has been inactive for 7 days since being marked as stale."
          days-before-pr-stale: 7
          days-before-pr-close: 7
          repo-token: ${{ secrets.GITHUB_TOKEN }}